import { createContext, useContext, useState, useCallback } from 'react';

export const LANGUAGES = { EN: 'en', BN: 'bn' };

export const translations = {
  en: {
    // HomePage
    // AboutPage
    aboutAyahTranslation:   '"Read in the name of your Lord who created" — Al-Alaq 96:1',
    aboutFoundationLabel:   'Our Foundation',
    aboutFoundationTitle:   'Nurturing Minds, Grounding Souls',
    aboutFoundationP1:      'Madinatul Ulum Tahfijul Quran Madrasah was established with a singular profound intention: to create an educational sanctuary where timeless Islamic wisdom seamlessly integrates with contemporary academic excellence. We believe that true education does not merely inform the mind, but transforms the character.',
    aboutFoundationP2:      'Madinatul Ulum Tahfijul Quran Madrasah strives to cultivate individuals who are both knowledgeable scholars and compassionate global citizens through a carefully balanced curriculum, dedicated mentorship, and an environment steeped in spiritual tranquility.',
    aboutHeritageTitle:     'Established Heritage',
    aboutHeritageDesc:      'Serving the community with dedication and upholding the highest standards of Islamic education.',
    aboutYearLabel:         'Year Established',
    aboutPrinciplesTitle:   'Guiding Principles',
    aboutMissionTitle:      'Our Mission',
    aboutMissionText:       'To provide a comprehensive educational experience that harmonizes authentic Islamic scholarship with modern academic disciplines, fostering an environment where spiritual growth and intellectual curiosity thrive together.',
    aboutVisionTitle:       'Our Vision',
    aboutVisionText:        'To be a beacon of holistic education, producing grounded, visionary leaders who carry the light of prophetic guidance into diverse professional fields, serving humanity with excellence and compassion.',
    aboutCtaTitle:          'Join Our Community',
    aboutCtaDesc:           'Whether you want to enroll a student, support our mission, or simply learn more — we welcome you.',
    aboutCtaAdmission:      'Admission Info',
    aboutCtaDonate:         'Donate Now',
    aboutCtaContact:        'Contact Us',
    // HomePage
    heroLocation:        'Barishal, Bangladesh',
    heroDesc:            'Islamic Education Institution based in Barishal, dedicated to nurturing minds with the light of the Quran and modern knowledge.',
    donateNowBtn:        'Donate Now',
    zakatCalcBtn:        'Zakat Calculator',
    admissionInfoBtn:    'Admission Info',
    heroImgCaption:      'Nurturing Hifz Students',
    heroImgSub:          'Providing quality Islamic education since 2018',
    whyChooseUs:         'Why Choose Us',
    whyChooseUsDesc:     'We provide a balanced environment where traditional Islamic values meet modern educational standards.',
    featureTeacherTitle: 'Qualified Teachers',
    featureTeacherDesc:  'Expert scholars and experienced educators dedicated to student success.',
    featureHifzTitle:    'Hifz Program',
    featureHifzDesc:     'Structured memorization of the Holy Quran with proper Tajweed.',
    featureEnvTitle:     'Islamic Environment',
    featureEnvDesc:      'A spiritual atmosphere fostering moral character and discipline.',
    activeDonations:     'Active Donation Projects',
    activeDonationsDesc: 'Support our ongoing initiatives and make a difference.',
    activeLabel:         'Active',
    raised:              'raised',
    donationCount:    'donations',
    donation:            'donation',
    statStudents:        'Students Enrolled',
    statDonations:       'Total Donations',
    statYears:           'Years of Excellence',
    statQuran:           'Quran Completion Rate',
    projectMadrasaTitle: 'Madrasa Development',
    projectMadrasaDesc:  'Build new classrooms, upgrade the library, and improve hostel facilities for our students.',
    projectMosqueTitle:  'Mosque Expansion',
    projectMosqueDesc:   "Expand the main prayer hall to accommodate our growing community for Jumu'ah and Tarawih.",
    projectSupportTitle: 'Student Support',
    projectSupportDesc:  'Provide tuition assistance, boarding support, and healthcare for underprivileged students.',
    // AdmissionPage
    admissionHeroTitle:       'Begin Your Journey of Knowledge',
    admissionHeroDesc:        'Discover a balanced educational environment where traditional Islamic scholarship meets modern academic excellence.',
    admissionProgramsTitle:   'Our Academic Programs',
    admissionProgramsDesc:    'Structured pathways for every stage of development.',
    admissionProgram1Title:   'Hifz Quran Program',
    admissionProgram1Desc:    'A dedicated, immersive program focused on the memorization, Tajweed, and foundational understanding of the Holy Quran under the guidance of experienced instructors.',
    admissionProgram1Tag1:    'Ages 8-14',
    admissionProgram1Tag2:    '3-4 Years Duration',
    admissionProgram2Title:   'Islamic Studies (Aalim)',
    admissionProgram2Desc:    'Comprehensive classical curriculum covering Fiqh, Hadith, Tafseer, and Arabic language for advanced scholarship.',
    admissionProgram2Tag1:    'Advanced Level',
    admissionCombinedTitle:   'Combined Excellence Program',
    admissionCombinedDesc:    'An integrated approach allowing students to pursue national curriculum education alongside core Islamic studies, ensuring graduates are well-equipped for modern professional life while remaining grounded in their faith.',
    admissionApplyNow:        'Apply Now',
    admissionReqTitle:        'Admission Requirements',
    admissionReqDesc:         'We seek dedicated students ready to commit to a rigorous and rewarding educational journey.',
    admissionReq1Title:       'Previous Academic Records',
    admissionReq1Desc:        'Original transcripts and transfer certificates from the most recently attended educational institution.',
    admissionReq2Title:       'Age Verification',
    admissionReq2Desc:        'Birth certificate or official identification document to verify placement in the appropriate age group.',
    admissionReq3Title:       'Entrance Interview',
    admissionReq3Desc:        'A brief assessment meeting with the student and parents to evaluate readiness and alignment with our institutional values.',
    admissionReq4Title:       'Medical Clearance',
    admissionReq4Desc:        'Standard health certificate verifying fitness to participate in regular campus activities and boarding (if applicable).',
    admissionFacilitiesTitle: 'Student Environment & Facilities',
    admissionFacilitiesDesc:  'Providing a safe, inspiring, and fully-equipped campus designed to support holistic development.',
    admissionFac1Title:       'Central Library',
    admissionFac1Desc:        'Extensive collection of classical Islamic texts, contemporary academic resources, and quiet study zones.',
    admissionFac2Title:       'Residential Hostel',
    admissionFac2Desc:        'Secure, comfortable boarding facilities with dedicated wardens, healthy dining, and disciplined routines.',
    admissionFac3Title:       'Modern Classrooms',
    admissionFac3Desc:        'Spacious, well-ventilated learning environments equipped to facilitate interactive and focused education.',
    admissionFormTitle:       'Ready to Apply?',
    admissionFormDesc:        'Admissions for the upcoming academic year are currently open. Fill in the form or contact us directly.',
    admissionContactPhone:    'Phone',
    admissionContactEmail:    'Email',
    admissionContactAddress:  'Address',
    admissionContactHours:    'Office Hours',
    admissionContactHoursVal: 'Sat–Thu, 9:00 AM – 4:00 PM',
    admissionInquiryTitle:    'Submit Admission Inquiry',
    admissionSuccess:         'Inquiry submitted! We will contact you within 2 working days.',
    admissionLabelName:       'Student / Parent Name *',
    admissionLabelPhone:      'Phone Number *',
    admissionLabelEmail:      'Email Address *',
    admissionLabelProgram:    'Program of Interest *',
    admissionLabelMessage:    'Additional Message',
    admissionPlaceholderName: 'Full name',
    admissionPlaceholderMsg:  'Any questions or additional information about the student...',
    admissionSubmit:          'Submit Inquiry',
    admissionSubmitting:      'Submitting…',
    // ContactPage
    contactHeroTitle:       'Get in Touch',
    contactHeroDesc:        'We are here to assist you. Reach out to us for any inquiries regarding donations, educational programs, or general support.',
    contactInfoTitle:       'Contact Information',
    contactAddress:         'Address',
    contactPhone:           'Phone',
    contactEmail:           'Email',
    contactOfficeHours:     'Office Hours',
    contactOfficeHoursVal:  'Sat–Thu\n9:00 AM – 4:00 PM',
    contactFormTitle:       'Send us a Message',
    contactSuccess:         'Message sent successfully! We will get back to you soon.',
    contactLabelName:       'Full Name *',
    contactLabelPhone:      'Phone Number',
    contactLabelEmail:      'Email Address *',
    contactLabelSubject:    'Subject *',
    contactLabelMessage:    'Your Message *',
    contactPlaceholderName: 'Enter your full name',
    contactPlaceholderEmail:'Enter your email',
    contactPlaceholderMsg:  'How can we help you today?',
    contactSending:         'Sending…',
    contactSend:            'Send Message',
    contactSubject1:        'General Inquiry',
    contactSubject2:        'Admission',
    contactSubject3:        'Donation',
    contactSubject4:        'Zakat',
    contactSubject5:        'Volunteering',
    contactSubject6:        'Other',
    // DonationPage
    donationHeroTitle:      'Make an Impact',
    donationHeroDesc:       'Your contribution helps us build a stronger community, support students, and maintain our sacred spaces.',
    donationCampaigns:      'Active Campaigns',
    donationRaised:         'raised',
    donationGoal:           'Goal',
    donationDonors:         'donors',
    donationDonor:          'donor',
    donationFunded:         'funded',
    donationSelected:       'Selected',
    donationSelectCampaign: 'Select Campaign',
    donationDetails:        'Details',
    donationFormTitle:      'Complete Donation',
    donationFormTo:         'Donating to:',
    donationSuccess:        'Donation recorded! JazakAllah Khair.',
    donationErrAmount:      'Please enter a valid amount.',
    donationSelectAmount:   'Select Amount',
    donationCustomAmount:   'Custom Amount',
    donationPaymentMethod:  'Payment Method',
    donationLabelName:      'Full Name',
    donationLabelEmail:     'Email Address',
    donationPlaceholderName:'Your name',
    donationAnonymousTitle: 'Make this donation anonymous',
    donationAnonymousDesc:  'Hide my name from public donor lists.',
    donationProcessing:     'Processing…',
    donationSecure:         'Secure, encrypted transaction',
    donationTagEducation:   'Education',
    donationTagInfra:       'Infrastructure',
    donationProject1Title:  'Student Support Fund',
    donationProject1Desc:   'Provide essential resources, books, and tuition assistance for underprivileged students in our Madrasa.',
    donationProject2Title:  'Mosque Expansion Project',
    donationProject2Desc:   "Help us expand the main prayer hall to accommodate our growing community for Jumu'ah and Tarawih.",
    donationProject3Title:  'Madrasa Development Fund',
    donationProject3Desc:   'Help us build and maintain world-class Islamic educational facilities for the next generation of scholars.',
    // MadrasaDonationPage
    madrasaBreadcrumbParent:  'Donations',
    madrasaBreadcrumbCurrent: 'Madrasa Development Fund',
    madrasaSupport:           'Support Our Mission',
    madrasaHeroTitle:         'Madrasa Development Fund',
    madrasaHeroDesc:          'Help us build and maintain world-class Islamic educational facilities for the next generation of scholars.',
    madrasaWhyTitle:          'Why Your Support Matters',
    madrasaItem1:             'Build new classrooms and learning spaces',
    madrasaItem2:             'Upgrade library with Islamic literature',
    madrasaItem3:             'Provide scholarships for deserving students',
    madrasaItem4:             'Maintain and improve hostel facilities',
    madrasaTotalRaised:       'Total Raised',
    madrasaDonors:            'Donors',
    madrasaPctGoal:           '% of goal',
    madrasaGoal:              'Goal',
    madrasaFormTitle:         'Donate to Madrasa Development',
    madrasaSuccess:           'Donation recorded! JazakAllah Khair.',
    madrasaErrAmount:         'Please enter a valid amount.',
    madrasaSelectAmount:      'Select Amount',
    madrasaCustomAmount:      'Custom Amount',
    madrasaPaymentMethod:     'Payment Method',
    madrasaLabelName:         'Full Name (optional)',
    madrasaProcessing:        'Processing…',
    madrasaExp1Title:         'New Classrooms',
    madrasaExp1Desc:          'Construction of modern, well-ventilated classrooms.',
    madrasaExp2Title:         'Library Upgrade',
    madrasaExp2Desc:          'Expanding Islamic literature and academic resources.',
    madrasaExp3Title:         'Student Scholarships',
    madrasaExp3Desc:          'Financial aid for deserving underprivileged students.',
    madrasaExp4Title:         'Hostel Facilities',
    madrasaExp4Desc:          'Maintenance and improvement of boarding facilities.',
    // MosqueDonationPage
    mosqueBreadcrumbParent:   'Donations',
    mosqueBreadcrumbCurrent:  'Mosque Expansion Fund',
    mosqueActiveProject:      'Active Project',
    mosqueHeroTitle:          'Grand Mosque Construction Phase II',
    mosqueHeroDesc:           'Building a lasting sanctuary for our community. Tracking our progress towards the structural completion of the main prayer hall.',
    mosqueFundingTitle:       'Funding Progress',
    mosqueRaisedOf:           'raised of',
    mosqueGoal:               'goal',
    mosqueFunded:             'Funded',
    mosqueRemaining:          'Remaining',
    mosqueTotalDonors:        'Total Donors',
    mosqueAvgDonation:        'Avg. Donation',
    mosqueStatus:             'Status',
    mosqueCompleted:          'Completed',
    mosqueOnTrack:            'On Track',
    mosqueSupportTitle:       'Support the House of Allah',
    mosqueSupportHadith:      '"Whoever builds a mosque for Allah, Allah will build for him a house like it in Paradise."',
    mosqueSuccess:            'Donation recorded! JazakAllah Khair.',
    mosqueErrAmount:          'Please enter a valid amount.',
    mosqueNamePlaceholder:    'Your Name (optional)',
    mosqueProcessing:         'Processing…',
    mosqueDonateNow:          'Donate Now',
    mosqueExpenseTitle:       'Expense Allocation',
    mosqueExp1Title:          'Foundation & Structure',
    mosqueExp1Desc:           'Concrete, steel, and structural engineering.',
    mosqueExp2Title:          'Exterior & Domes',
    mosqueExp2Desc:           'Marble cladding, dome construction, minarets.',
    mosqueExp3Title:          'Interior & Carpentry',
    mosqueExp3Desc:           'Mihrab, minbar, calligraphy, and carpeting.',
    mosqueExp4Title:          'Utilities & HVAC',
    mosqueExp4Desc:           'Lighting, climate control, sound systems.',
    // StudentSupportDonationPage
    studentBreadcrumbParent:  'Donations',
    studentBreadcrumbCurrent: 'Student Support Fund',
    studentHeroTitle:         'Student Support Fund',
    studentHeroDesc:          'Manage and track donations dedicated to student financial aid, scholarships, and resources.',
    studentGoalTitle:         'Annual Scholarship Goal',
    studentGoalYear:          'Target for 2024 Academic Year',
    studentOnTrack:           'On Track',
    studentFunded:            'Funded',
    studentRemaining:         'Remaining',
    studentTotalDonors:       'Total Donors',
    studentAvgGift:           'Avg. Gift',
    studentAided:             'Students Aided',
    studentAllocationTitle:   'Fund Allocation',
    studentAlloc1:            'Tuition Assistance',
    studentAlloc1Desc:        'Direct tuition fee support for students who cannot afford education.',
    studentAlloc2:            'Boarding & Meals',
    studentAlloc2Desc:        'Hostel accommodation and daily nutritious meals for residential students.',
    studentAlloc3:            'Healthcare',
    studentAlloc3Desc:        'Medical checkups, treatment, and health support for all students.',
    studentFormTitle:         'Make a Contribution',
    studentSuccess:           'Donation recorded! JazakAllah Khair.',
    studentErrAmount:         'Please enter a valid amount.',
    studentLabelName:         'Your Name (optional)',
    studentLabelAmount:       'Donation Amount',
    studentCustomAmount:      'Custom Amount',
    studentPaymentMethod:     'Payment Method',
    studentProcessing:        'Processing…',
    // public nav
    home:           'Home',
    about:          'About',
    admission:      'Admission',
    donations:      'Donations',
    zakat:          'Zakat',
    gallery:        'Gallery',
    transparency:   'Transparency',
    language:       'Language',
    contact:        'Contact',
    donateNow:      'Donate Now',
    // admin nav
    dashboard:      'Dashboard',
    madrasaMgmt:    'Madrasa Mgmt',
    students:       'Students',
    studentFinance: 'Student Finance',
    adminDonations: 'Admin Donations',
    adminZakat:     'Zakat Management',
    programs:       'Programs',
    adminLanguage:  'Language',
    reports:        'Reports',
    users:          'Users',
    settings:       'Settings',
    support:        'Support',
    logout:         'Logout',
    adminPortal:    'Admin Portal',
    adminConsole:   'Admin Console',
    search:         'Search…',
    // ZakatCalculatorPage
    zakatPageTitle:       'Zakat Calculator',
    zakatPageDesc:        'Calculate your Zakat accurately based on Islamic Shariah principles. Enter your assets below.',
    zakatNisabInfo:       'Nisab threshold (Silver)',
    zakatRate:            'Rate: 2.5%',
    zakatAssetsTitle:     'Your Zakatable Assets',
    zakatAssetsSubtitle:  'Enter amounts held for one full lunar year (Hawl)',
    zakatCalculate:       'Calculate Zakat',
    zakatCalculating:     'Calculating…',
    zakatRulesTitle:      'Islamic Zakat Rules',
    zakatRule1:           'Hawl: Wealth must be held for one full lunar year',
    zakatRule2:           'Nisab: Minimum threshold based on 612.36g of silver',
    zakatRule3:           'Rate: 2.5% of total net zakatable wealth',
    zakatRule4:           'Zakatable: Cash, gold, silver, investments, trade goods',
    zakatRule5:           'Deductible: Immediate debts due within the year',
    zakatRule6:           'Not zakatable: Personal home, car, clothing, furniture',
    zakatNisabMet:        'Nisab Threshold Met — Zakat is Obligatory',
    zakatNisabNotMet:     'Nisab Not Met — Zakat Not Obligatory',
    zakatNisabLabel:      'Nisab',
    zakatNetWealth:       'Your net wealth',
    zakatBreakdownTitle:  'Wealth Breakdown',
    zakatTotalAssets:     'Total Assets',
    zakatGoldValue:       'Gold Value',
    zakatSilverValue:     'Silver Value',
    zakatLessDebts:       'Less: Debts',
    zakatNetWealthLabel:  'Net Wealth',
    zakatDueTitle:        'Total Zakat Due',
    zakatAllocateTo:      'Allocate To',
    zakatPaymentMethod:   'Payment Method',
    zakatDonorPlaceholder:'Your name (optional)',
    zakatRecorded:        'Zakat recorded! JazakAllah Khair.',
    zakatDonateBtn:       'Donate',
    zakatDonateNow:       'Now',
    zakatProcessing:      'Processing…',
    zakatErrZero:         'Your Zakat amount is ৳0. Please enter your assets first.',
    zakatFieldCash:       'Cash, Bank Savings & Deposits',
    zakatFieldCashHint:   'Include all cash at home and in bank accounts',
    zakatFieldGold:       'Gold (in grams)',
    zakatFieldGoldHint:   'Enter weight in grams — value calculated at current rate (৳9,500/g)',
    zakatFieldSilver:     'Silver (in grams)',
    zakatFieldSilverHint: 'Enter weight in grams — value calculated at current rate (৳110/g)',
    zakatFieldInvest:     'Investments & Shares',
    zakatFieldInvestHint: 'Stocks, mutual funds, and other investments at current market value',
    zakatFieldBusiness:   'Business Goods & Inventory',
    zakatFieldBusinessHint:'Value of goods held for trade at current market price',
    zakatFieldReceivable: 'Money Owed to You',
    zakatFieldReceivableHint:'Loans given out that you expect to receive back',
    zakatFieldDebts:      'Deductible Debts',
    zakatFieldDebtsHint:  'Immediate debts due within the year (not long-term mortgages)',
    zakatAlloc1:          'General Fund (Most Needed)',
    zakatAlloc1Desc:      'Distributed where most needed',
    zakatAlloc2:          'Student Sponsorship',
    zakatAlloc2Desc:      "Support students' education",
    zakatAlloc3:          'Madrasa Maintenance',
    zakatAlloc3Desc:      'Upkeep of facilities',
    zakatAlloc4:          'Islamic Education Materials',
    zakatAlloc4Desc:      'Books and learning resources',
    // TransparencyDashboardPage
    transFinancialOverview:   'Financial Overview',
    transHeroTitle:           'Transparency & Impact',
    transHeroDesc:            'We believe in complete accountability. Explore our real-time financial distribution, project expenses, and operational integrity.',
    transTotalDonations:      'Total Donations',
    transTotalDonors:         'total donors',
    transZakatCollected:      'Zakat Collected',
    transZakatVerified:       'Verified & distributed',
    transActiveStudents:      'Active Students',
    transCurrentlyEnrolled:   'Currently enrolled',
    transFundDistTitle:       'Fund Distribution by Project',
    transMonthlyTitle:        'Monthly Donations (Last 6 Months)',
    transNoData:              'No donation data yet.',
    transNoMonthly:           'No monthly data available.',
    transProjectTitle:        'Project Breakdown',
    transColProject:          'Project',
    transColRaised:           'Total Raised',
    transColGoal:             'Goal',
    transColProgress:         'Progress',
    transColDonations:        'Donations',
    transColStatus:           'Status',
    transNoProject:           'No project data available.',
    transStatusCompleted:     'Completed',
    transStatusInProgress:    'In Progress',
    transStatusOngoing:       'Ongoing',
    transZakatFund:           'Zakat Fund',
    transZakatDistributed:    'Verified & distributed to eligible recipients',
    transShariahCompliant:    'Shariah Compliant',
    transShariahDesc:         'All Zakat distributed per Islamic guidelines',
    transDocsTitle:           'Official Documents',
    transDoc1:                'Annual Report 2023',
    transDoc1Size:            'PDF • 4.2 MB',
    transDoc2:                'Q1 Financials 2024',
    transDoc2Size:            'PDF • 1.1 MB',
    transDoc3:                'Audit Certificate',
    transDoc3Size:            'PDF • 0.8 MB',
    transDoc4:                'Zakat Policy',
    transDoc4Size:            'PDF • 2.5 MB',
    transTotal:               'Total',
    // PhotoGalleryPage
    galleryTitle:             'Visual Chronicles',
    galleryDesc:              'A glimpse into our vibrant community, educational milestones, and the profound impact of your generous contributions.',
    galleryFilterAll:         'All',
    galleryFilterQuran:       'Quran Learning',
    galleryFilterClassroom:   'Classroom',
    galleryFilterEvents:      'Events',
    galleryFilterStudentLife: 'Student Life',
    galleryEmpty:             'No photos in this category yet.',
    galleryLoadMore:          'Load More',
    galleryRemaining:         'remaining',
    // NotFoundPage
    notFoundTitle:    'Page Not Found',
    notFoundDesc:     'The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.',
    notFoundReturn:   'Return Home',
    notFoundContact:  'Contact Support',
    notFoundFooter:   '© 2024 Madinatul Ulum Tahfijul Quran Madrasah. All rights reserved.',
    // Footer
    footerTagline:      'Dedicated to nurturing minds and souls through authentic Islamic education and compassionate charity.',
    footerLicense:      'Licensed NGO.',
    footerDonateTitle:  'Donate',
    footerQuickTitle:   'Quick Links',
    footerTransTitle:   'Transparency',
    footerLink1:        'Contact Us',
    footerLink2:        'Admission Portal',
    footerLink3:        'About Us',
    footerLink4:        'Photo Gallery',
    footerLink5:        'Transparency',
    footerInfo1:        'Transparency Dashboard',
    footerInfo2:        'Photo Gallery',
    footerInfo3:        'Zakat Calculator',
    footerDon1:         'All Campaigns',
    footerDon2:         'Madrasa Development Fund',
    footerDon3:         'Mosque Expansion Fund',
    footerDon4:         'Student Support Fund',
  },
  bn: {
    // HomePage
    // AboutPage
    aboutAyahTranslation:   '"পড়ো তোমার প্রভুর নামে যিনি সৃষ্টি করেছেন" — সূরা আলাক ৯৬:১',
    aboutFoundationLabel:   'আমাদের প্রতিষ্ঠা',
    aboutFoundationTitle:   'মন গড়াও, আত্মা শাণিত করো',
    aboutFoundationP1:      'মাদিনাতুল উলুম তাহফিজুল কোরআন মাদ্রাসা একটি গভীর সংকল্প নিয়ে প্রতিষ্ঠিত হয়েছিল: এমন একটি শিক্ষার আশ্রয় তৈরি করা যেখানে চিরন্তন ইসলামিক জ্ঞান আধুনিক শিক্ষাগত উৎকর্ষের সাথে সুসমন্বিতভাবে মিশে যায়। আমরা বিশ্বাস করি যে প্রকৃত শিক্ষা কেবল মনকে তথ্য দেয় না, বরং চরিত্রকে রূপান্তরিত করে।',
    aboutFoundationP2:      'মাদিনাতুল উলুম তাহফিজুল কোরআন মাদ্রাসা যত্নশীলভাবে সুষম পাঠ্যক্রম, নিবেদিত প্রশিক্ষণ এবং আধ্যাত্মিক পরিবেশের মাধ্যমে এমন ব্যক্তি গড়ে তুলতে চেষ্টা করে যারা হবেন জ্ঞানী আলেম এবং দয়ালু বৈশ্বিক নাগরিক।',
    aboutHeritageTitle:     'প্রতিষ্ঠিত ঐতিহ্য',
    aboutHeritageDesc:      'নিষ্ঠার সাথে সমাজের সেবা করে ইসলামিক শিক্ষার সর্বোচ্চ মান বজায় রাখা।',
    aboutYearLabel:         'প্রতিষ্ঠার বছর',
    aboutPrinciplesTitle:   'পরিচালনার নীতিমালা',
    aboutMissionTitle:      'আমাদের লক্ষ্য',
    aboutMissionText:       'প্রকৃত ইসলামিক বিদ্যাচর্চাকে আধুনিক শিক্ষাবিদ্যার সাথে সমন্বয় করে একটি সম্পূর্ণ শিক্ষামূলক অভিজ্ঞতা প্রদান করা, যেখানে আধ্যাত্মিক বিকাশ ও বৌদ্ধিক কৌতূহল একসাথে বিকশিত হয়।',
    aboutVisionTitle:       'আমাদের দৃষ্টিভঙ্গি',
    aboutVisionText:        'সমগ্রমুখী শিক্ষার একটি আলোকবর্তিকা হওয়া, যা দৃঢ়চেতা ও দূরদর্শী নেতা তৈরি করবে যারা নবীয় দিকনির্দেশনার আলো বিভিন্ন পেশাদার ক্ষেত্রে বহন করবে এবং শ্রেষ্ঠত্ব ও সহমর্মিতার সাথে মানবজাতির সেবা করবে।',
    aboutCtaTitle:          'আমাদের সমাজে যোগ দিন',
    aboutCtaDesc:           'আপনি যদি শিক্ষার্থী ভর্তি করতে, আমাদের মিশন সমর্থন করতে, বা শুধু আরও জানতে চান — আমরা আপনাকে স্বাগত জানাই।',
    aboutCtaAdmission:      'ভর্তি তথ্য',
    aboutCtaDonate:         'এখনই দান করুন',
    aboutCtaContact:        'যোগাযোগ করুন',
    // HomePage
    heroLocation:        'বরিশাল, বাংলাদেশ',
    heroDesc:            'বরিশালে অবস্থিত একটি ইসলামী শিক্ষা প্রতিষ্ঠান, যা কোরআনের আলো ও আধুনিক জ্ঞানে শিক্ষার্থীদের গড়ে তুলতে নিবেদিত।',
    donateNowBtn:        'এখনই দান করুন',
    zakatCalcBtn:        'যাকাত ক্যালকুলেটর',
    admissionInfoBtn:    'ভর্তি তথ্য',
    heroImgCaption:      'হিফজ শিক্ষার্থীদের লালন-পালন',
    heroImgSub:          '২০১৮ সাল থেকে মানসম্পন্ন ইসলামী শিক্ষা প্রদান করছে',
    whyChooseUs:         'কেন আমাদের বেছে নেবেন',
    whyChooseUsDesc:     'আমরা এমন একটি সুষম পরিবেশ প্রদান করি যেখানে ঐতিহ্যবাহী ইসলামী মূল্যবোধ আধুনিক শিক্ষার মানদণ্ডের সাথে মিলিত হয়।',
    featureTeacherTitle: 'যোগ্য শিক্ষকমণ্ডলী',
    featureTeacherDesc:  'শিক্ষার্থীদের সাফল্যে নিবেদিত বিশেষজ্ঞ আলেম ও অভিজ্ঞ শিক্ষকবৃন্দ।',
    featureHifzTitle:    'হিফজ প্রোগ্রাম',
    featureHifzDesc:     'সঠিক তাজবিদসহ পবিত্র কোরআনের কাঠামোবদ্ধ মুখস্থকরণ।',
    featureEnvTitle:     'ইসলামী পরিবেশ',
    featureEnvDesc:      'নৈতিক চরিত্র ও শৃঙ্খলা গঠনে সহায়ক আধ্যাত্মিক পরিবেশ।',
    activeDonations:     'সক্রিয় দান প্রকল্পসমূহ',
    activeDonationsDesc: 'আমাদের চলমান উদ্যোগগুলো সমর্থন করুন এবং পরিবর্তন আনুন।',
    activeLabel:         'সক্রিয়',
    raised:              'সংগৃহীত',
    donationCount:    'টি দান',
    donation:            'টি দান',
    statStudents:        'নিবন্ধিত শিক্ষার্থী',
    statDonations:       'মোট দান',
    statYears:           'বছরের শ্রেষ্ঠত্ব',
    statQuran:           'কোরআন সমাপ্তির হার',
    projectMadrasaTitle: 'মাদ্রাসা উন্নয়ন',
    projectMadrasaDesc:  'শিক্ষার্থীদের জন্য নতুন শ্রেণিকক্ষ নির্মাণ, লাইব্রেরি উন্নয়ন এবং হোস্টেল সুবিধা উন্নত করুন।',
    projectMosqueTitle:  'মসজিদ সম্প্রসারণ',
    projectMosqueDesc:   'জুমআ ও তারাবিহর জন্য ক্রমবর্ধমান মুসল্লিদের ধারণ করতে প্রধান নামাজ হল সম্প্রসারণ করুন।',
    projectSupportTitle: 'শিক্ষার্থী সহায়তা',
    projectSupportDesc:  'সুবিধাবঞ্চিত শিক্ষার্থীদের জন্য টিউশন সহায়তা, আবাসন সহায়তা এবং স্বাস্থ্যসেবা প্রদান করুন।',
    // AdmissionPage
    admissionHeroTitle:       'জ্ঞানের পথে আপনার যাত্রা শুরু করুন',
    admissionHeroDesc:        'এমন একটি সুষম শিক্ষামূলক পরিবেশ আবিষ্কার করুন যেখানে ঐতিহ্যবাহী ইসলামী বিদ্যাচর্চা আধুনিক শিক্ষাগত উৎকর্ষের সাথে মিলিত হয়।',
    admissionProgramsTitle:   'আমাদের একাডেমিক প্রোগ্রামসমূহ',
    admissionProgramsDesc:    'প্রতিটি বিকাশের স্তরের জন্য কাঠামোবদ্ধ পথ।',
    admissionProgram1Title:   'হিফজ কোরআন প্রোগ্রাম',
    admissionProgram1Desc:    'অভিজ্ঞ শিক্ষকদের তত্ত্বাবধানে পবিত্র কোরআনের মুখস্থকরণ, তাজবিদ এবং মৌলিক বোঝাপড়ার উপর নিবেদিত একটি নিমজ্জিত প্রোগ্রাম।',
    admissionProgram1Tag1:    'বয়স ৮-১৪',
    admissionProgram1Tag2:    '৩-৪ বছর মেয়াদ',
    admissionProgram2Title:   'ইসলামী শিক্ষা (আলিম)',
    admissionProgram2Desc:    'উচ্চতর বিদ্যাচর্চার জন্য ফিকহ, হাদিস, তাফসির এবং আরবি ভাষা অন্তর্ভুক্ত ব্যাপক ক্লাসিক্যাল পাঠ্যক্রম।',
    admissionProgram2Tag1:    'উচ্চতর স্তর',
    admissionCombinedTitle:   'সমন্বিত শ্রেষ্ঠত্ব প্রোগ্রাম',
    admissionCombinedDesc:    'একটি সমন্বিত পদ্ধতি যা শিক্ষার্থীদের মূল ইসলামী শিক্ষার পাশাপাশি জাতীয় পাঠ্যক্রম শিক্ষা অনুসরণ করতে দেয়, নিশ্চিত করে যে স্নাতকরা বিশ্বাসে প্রোথিত থেকে আধুনিক পেশাদার জীবনের জন্য সুসজ্জিত।',
    admissionApplyNow:        'এখনই আবেদন করুন',
    admissionReqTitle:        'ভর্তির প্রয়োজনীয়তা',
    admissionReqDesc:         'আমরা এমন নিবেদিত শিক্ষার্থী খুঁজি যারা একটি কঠোর ও ফলপ্রসূ শিক্ষামূলক যাত্রায় প্রতিশ্রুতিবদ্ধ হতে প্রস্তুত।',
    admissionReq1Title:       'পূর্ববর্তী একাডেমিক রেকর্ড',
    admissionReq1Desc:        'সর্বশেষ পড়া শিক্ষা প্রতিষ্ঠান থেকে মূল ট্রান্সক্রিপ্ট এবং ট্রান্সফার সার্টিফিকেট।',
    admissionReq2Title:       'বয়স যাচাইকরণ',
    admissionReq2Desc:        'উপযুক্ত বয়স গ্রুপে স্থান নিশ্চিত করতে জন্ম সনদ বা সরকারি পরিচয়পত্র।',
    admissionReq3Title:       'ভর্তি সাক্ষাৎকার',
    admissionReq4Title:       'চিকিৎসা ছাড়পত্র',
    admissionReq3Desc:        'শিক্ষার্থী ও অভিভাবকদের সাথে প্রস্তুতি এবং প্রাতিষ্ঠানিক মূল্যবোধের সাথে সামঞ্জস্য মূল্যায়নের জন্য একটি সংক্ষিপ্ত মূল্যায়ন সভা।',
    admissionReq4Desc:        'নিয়মিত ক্যাম্পাস কার্যক্রম ও আবাসনে (প্রযোজ্য হলে) অংশগ্রহণের যোগ্যতা যাচাইকারী স্বাস্থ্য সনদ।',
    admissionFacilitiesTitle: 'শিক্ষার্থী পরিবেশ ও সুযোগ-সুবিধা',
    admissionFacilitiesDesc:  'সামগ্রিক বিকাশ সমর্থনের জন্য ডিজাইন করা একটি নিরাপদ, অনুপ্রেরণামূলক এবং সম্পূর্ণ সজ্জিত ক্যাম্পাস।',
    admissionFac1Title:       'কেন্দ্রীয় লাইব্রেরি',
    admissionFac1Desc:        'ক্লাসিক্যাল ইসলামী গ্রন্থ, সমসাময়িক একাডেমিক সম্পদ এবং শান্ত অধ্যয়ন অঞ্চলের বিশাল সংগ্রহ।',
    admissionFac2Title:       'আবাসিক হোস্টেল',
    admissionFac2Desc:        'নিবেদিত ওয়ার্ডেন, স্বাস্থ্যকর খাবার এবং শৃঙ্খলাবদ্ধ রুটিন সহ নিরাপদ ও আরামদায়ক আবাসন সুবিধা।',
    admissionFac3Title:       'আধুনিক শ্রেণিকক্ষ',
    admissionFac3Desc:        'ইন্টারেক্টিভ ও মনোযোগী শিক্ষা সহজতর করতে সজ্জিত প্রশস্ত, সুবায়ুযুক্ত শিক্ষার পরিবেশ।',
    admissionFormTitle:       'আবেদন করতে প্রস্তুত?',
    admissionFormDesc:        'আসন্ন শিক্ষাবর্ষের ভর্তি বর্তমানে খোলা আছে। ফর্মটি পূরণ করুন বা সরাসরি আমাদের সাথে যোগাযোগ করুন।',
    admissionContactPhone:    'ফোন',
    admissionContactEmail:    'ইমেইল',
    admissionContactAddress:  'ঠিকানা',
    admissionContactHours:    'অফিস সময়',
    admissionContactHoursVal: 'শনি–বৃহস্পতি, সকাল ৯:০০ – বিকাল ৪:০০',
    admissionInquiryTitle:    'ভর্তি অনুসন্ধান জমা দিন',
    admissionSuccess:         'অনুসন্ধান জমা হয়েছে! আমরা ২ কার্যদিবসের মধ্যে আপনার সাথে যোগাযোগ করব।',
    admissionLabelName:       'শিক্ষার্থী / অভিভাবকের নাম *',
    admissionLabelPhone:      'ফোন নম্বর *',
    admissionLabelEmail:      'ইমেইল ঠিকানা *',
    admissionLabelProgram:    'আগ্রহের প্রোগ্রাম *',
    admissionLabelMessage:    'অতিরিক্ত বার্তা',
    admissionPlaceholderName: 'পূর্ণ নাম',
    admissionPlaceholderMsg:  'শিক্ষার্থী সম্পর্কে যেকোনো প্রশ্ন বা অতিরিক্ত তথ্য...',
    admissionSubmit:          'অনুসন্ধান জমা দিন',
    admissionSubmitting:      'জমা হচ্ছে…',
    // ContactPage
    contactHeroTitle:       'যোগাযোগ করুন',
    contactHeroDesc:        'আমরা আপনাকে সহায়তা করতে এখানে আছি। দান, শিক্ষামূলক কার্যক্রম বা সাধারণ সহায়তা সংক্রান্ত যেকোনো জিজ্ঞাসায় আমাদের সাথে যোগাযোগ করুন।',
    contactInfoTitle:       'যোগাযোগের তথ্য',
    contactAddress:         'ঠিকানা',
    contactPhone:           'ফোন',
    contactEmail:           'ইমেইল',
    contactOfficeHours:     'অফিস সময়',
    contactOfficeHoursVal:  'শনি–বৃহস্পতি\nসকাল ৯:০০ – বিকাল ৪:০০',
    contactFormTitle:       'আমাদের বার্তা পাঠান',
    contactSuccess:         'বার্তা সফলভাবে পাঠানো হয়েছে! আমরা শীঘ্রই আপনার সাথে যোগাযোগ করব।',
    contactLabelName:       'পূর্ণ নাম *',
    contactLabelPhone:      'ফোন নম্বর',
    contactLabelEmail:      'ইমেইল ঠিকানা *',
    contactLabelSubject:    'বিষয় *',
    contactLabelMessage:    'আপনার বার্তা *',
    contactPlaceholderName: 'আপনার পূর্ণ নাম লিখুন',
    contactPlaceholderEmail:'আপনার ইমেইল লিখুন',
    contactPlaceholderMsg:  'আজ আমরা আপনাকে কীভাবে সাহায্য করতে পারি?',
    contactSending:         'পাঠানো হচ্ছে…',
    contactSend:            'বার্তা পাঠান',
    contactSubject1:        'সাধারণ জিজ্ঞাসা',
    contactSubject2:        'ভর্তি',
    contactSubject3:        'দান',
    contactSubject4:        'যাকাত',
    contactSubject5:        'স্বেচ্ছাসেবা',
    contactSubject6:        'অন্যান্য',
    // DonationPage
    donationHeroTitle:      'পরিবর্তন আনুন',
    donationHeroDesc:       'আপনার অবদান আমাদের শক্তিশালী সমাজ গড়তে, শিক্ষার্থীদের সহায়তা করতে এবং আমাদের পবিত্র স্থানগুলো রক্ষণাবেক্ষণ করতে সহায়তা করে।',
    donationCampaigns:      'সক্রিয় ক্যাম্পেইনসমূহ',
    donationRaised:         'সংগৃহীত',
    donationGoal:           'লক্ষ্য',
    donationDonors:         'জন দাতা',
    donationDonor:          'জন দাতা',
    donationFunded:         'সংগ্রহ',
    donationSelected:       'নির্বাচিত',
    donationSelectCampaign: 'ক্যাম্পেইন বেছুন',
    donationDetails:        'বিস্তারিত',
    donationFormTitle:      'দান সম্পন্ন করুন',
    donationFormTo:         'যার জন্য দান:',
    donationSuccess:        'দান নথিভুক্ত হয়েছে! জাজাকাল্লাহ খাইর।',
    donationErrAmount:      'অনুগ্রহ করে সঠিক পরিমাণ লিখুন।',
    donationSelectAmount:   'পরিমাণ নির্বাচন করুন',
    donationCustomAmount:   'ইচ্ছামতো পরিমাণ',
    donationPaymentMethod:  'পেমেন্ট পদ্ধতি',
    donationLabelName:      'পূর্ণ নাম',
    donationLabelEmail:     'ইমেইল ঠিকানা',
    donationPlaceholderName:'আপনার নাম',
    donationAnonymousTitle: 'এই দানটি বেনামী করুন',
    donationAnonymousDesc:  'পাবলিক দাতা তালিকা থেকে আমার নাম লুকান।',
    donationProcessing:     'প্রক্রিয়া হচ্ছে…',
    donationSecure:         'নিরাপদ, স্তরের লেনদেন',
    donationTagEducation:   'শিক্ষা',
    donationTagInfra:       'অবকাঠামো',
    donationProject1Title:  'শিক্ষার্থী সহায়তা তহবিল',
    donationProject1Desc:   'মাদ্রাসার সুবিধাবঞ্চিত শিক্ষার্থীদের জন্য প্রয়োজনীয় সম্পদ, বই এবং টিউশন সহায়তা প্রদান করুন।',
    donationProject2Title:  'মসজিদ সম্প্রসারণ প্রকল্প',
    donationProject2Desc:   'জুমআ ও তারাবিহর জন্য ক্রমবর্ধমান মুসল্লিদের ধারণ করতে প্রধান নামাজ হল সম্প্রসারিত করতে সহায়তা করুন।',
    donationProject3Title:  'মাদ্রাসা উন্নয়ন তহবিল',
    donationProject3Desc:   'ভবিষ্যত প্রজন্মের আলেমদের জন্য বিশ্বমানের ইসলামি শিক্ষা সুবিধা নির্মাণ ও রক্ষণাবেক্ষণে সহায়তা করুন।',
    // MadrasaDonationPage
    madrasaBreadcrumbParent:  'দান',
    madrasaBreadcrumbCurrent: 'মাদ্রাসা উন্নয়ন তহবিল',
    madrasaSupport:           'আমাদের মিশন সমর্থন করুন',
    madrasaHeroTitle:         'মাদ্রাসা উন্নয়ন তহবিল',
    madrasaHeroDesc:          'ভবিষ্যত প্রজন্মের আলেমদের জন্য বিশ্বমানের ইসলামি শিক্ষা সুবিধা নির্মাণ ও রক্ষণাবেক্ষণে সহায়তা করুন।',
    madrasaWhyTitle:          'আপনার সহায়তা কেন গুরুত্বপূর্ণ',
    madrasaItem1:             'নতুন শ্রেণিকক্ষ ও শিক্ষার পরিবেশ নির্মাণ করুন',
    madrasaItem2:             'ইসলামি সাহিত্য দিয়ে লাইব্রেরি উন্নত করুন',
    madrasaItem3:             'যোগ্য শিক্ষার্থীদের জন্য বৃত্তি প্রদান করুন',
    madrasaItem4:             'হোস্টেল সুবিধা রক্ষণাবেক্ষণ ও উন্নত করুন',
    madrasaTotalRaised:       'মোট সংগৃহীত',
    madrasaDonors:            'দাতা',
    madrasaPctGoal:           '% লক্ষ্যমাত্রা',
    madrasaGoal:              'লক্ষ্য',
    madrasaFormTitle:         'মাদ্রাসা উন্নয়নে দান করুন',
    madrasaSuccess:           'দান নথিভুক্ত হয়েছে! জাজাকাল্লাহ খাইর।',
    madrasaErrAmount:         'অনুগ্রহ করে সঠিক পরিমাণ লিখুন।',
    madrasaSelectAmount:      'পরিমাণ নির্বাচন করুন',
    madrasaCustomAmount:      'ইচ্ছামতো পরিমাণ',
    madrasaPaymentMethod:     'পেমেন্ট পদ্ধতি',
    madrasaLabelName:         'পূর্ণ নাম (ঐচ্ছিক)',
    madrasaProcessing:        'প্রক্রিয়া হচ্ছে…',
    madrasaExp1Title:         'নতুন শ্রেণিকক্ষ',
    madrasaExp1Desc:          'আধুনিক, সুবায়ুযুক্ত শ্রেণিকক্ষ নির্মাণ।',
    madrasaExp2Title:         'লাইব্রেরি উন্নয়ন',
    madrasaExp2Desc:          'ইসলামি সাহিত্য ও শিক্ষামূলক সম্পদ সম্প্রসারণ।',
    madrasaExp3Title:         'শিক্ষার্থী বৃত্তি',
    madrasaExp3Desc:          'যোগ্য সুবিধাবঞ্চিত শিক্ষার্থীদের জন্য আর্থিক সহায়তা।',
    madrasaExp4Title:         'হোস্টেল সুবিধা',
    madrasaExp4Desc:          'আবাসিক সুবিধার রক্ষণাবেক্ষণ ও উন্নয়ন।',
    // MosqueDonationPage
    mosqueBreadcrumbParent:   'দান',
    mosqueBreadcrumbCurrent:  'মসজিদ সম্প্রসারণ তহবিল',
    mosqueActiveProject:      'সক্রিয় প্রকল্প',
    mosqueHeroTitle:          'গ্রান্ড মসজিদ নির্মাণ দ্বিতীয় পর্যায়',
    mosqueHeroDesc:           'আমাদের সমাজের জন্য একটি চিরস্থায়ী আশ্রয় নির্মাণ করা হচ্ছে। প্রধান নামাজ হলের কাঠামোগত সমাপ্তির দিকে আমাদের অগ্রগতি পর্যবেক্ষণ করা হচ্ছে।',
    mosqueFundingTitle:       'তহবিল সংগ্রহের অগ্রগতি',
    mosqueRaisedOf:           'সংগৃহীত',
    mosqueGoal:               'লক্ষ্যমাত্রার',
    mosqueFunded:             'সংগ্রহ',
    mosqueRemaining:          'বাকি',
    mosqueTotalDonors:        'মোট দাতা',
    mosqueAvgDonation:        'গড় দান',
    mosqueStatus:             'অবস্থা',
    mosqueCompleted:          'সম্পন্ন',
    mosqueOnTrack:            'চলমান',
    mosqueSupportTitle:       'আল্লাহর ঘর সমর্থন করুন',
    mosqueSupportHadith:      '“যে ব্যক্তি আল্লাহর জন্য একটি মসজিদ নির্মাণ করে, আল্লাহ জান্নাতে তার জন্য তদ্রূপ একটি ঘর নির্মাণ করবেন।”',
    mosqueSuccess:            'দান নথিভুক্ত হয়েছে! জাজাকাল্লাহ খাইর।',
    mosqueErrAmount:          'অনুগ্রহ করে সঠিক পরিমাণ লিখুন।',
    mosqueNamePlaceholder:    'আপনার নাম (ঐচ্ছিক)',
    mosqueProcessing:         'প্রক্রিয়া হচ্ছে…',
    mosqueDonateNow:          'এখনই দান করুন',
    mosqueExpenseTitle:       'ব্যয় বরাদ্দ',
    mosqueExp1Title:          'ভিত্তি ও কাঠামো',
    mosqueExp1Desc:           'কংক্রিট, স্টিল এবং কাঠামোগত প্রকৌশল।',
    mosqueExp2Title:          'বাহ্যিক অবকাঠামো ও গম্বুজ',
    mosqueExp2Desc:           'মারবেল ক্ল্যাডিং, গম্বুজ নির্মাণ, মিনারেত।',
    mosqueExp3Title:          'আন্তরীণ সজ্জা ও কারপেন্ট্রি',
    mosqueExp3Desc:           'মিহরাব, মিম্বার, ক্যালিগ্রাফি এবং কার্পেটিং।',
    mosqueExp4Title:          'ইউটিলিটি ও এইচভিএসি',
    mosqueExp4Desc:           'আলোকসজ্জা, তাপমাত্রা নিয়ন্ত্রণ, শব্দ ব্যবস্থা।',
    // StudentSupportDonationPage
    studentBreadcrumbParent:  'দান',
    studentBreadcrumbCurrent: 'শিক্ষার্থী সহায়তা তহবিল',
    studentHeroTitle:         'শিক্ষার্থী সহায়তা তহবিল',
    studentHeroDesc:          'শিক্ষার্থীদের আর্থিক সহায়তা, বৃত্তি এবং সম্পদের জন্য নিবেদিত দান পরিচালনা ও পর্যবেক্ষণ করুন।',
    studentGoalTitle:         'বার্ষিক বৃত্তি লক্ষ্য',
    studentGoalYear:          '২০২৪ শিক্ষাবর্ষের লক্ষ্যমাত্রা',
    studentOnTrack:           'সঠিক পথে',
    studentFunded:            'সংগ্রহ',
    studentRemaining:         'বাকি',
    studentTotalDonors:       'মোট দাতা',
    studentAvgGift:           'গড় দান',
    studentAided:             'সহায়তাপ্রাপ্ত শিক্ষার্থী',
    studentAllocationTitle:   'তহবিল বরাদ্দ',
    studentAlloc1:            'টিউশন সহায়তা',
    studentAlloc1Desc:        'যেসব শিক্ষার্থী পড়াশোনার খরচ বহন করতে পারে না তাদের সরাসরি টিউশন ফি সহায়তা।',
    studentAlloc2:            'আবাসন ও খাবার',
    studentAlloc2Desc:        'আবাসিক শিক্ষার্থীদের জন্য হোস্টেল আবাসন ও দৈনিক পুষ্টিকর খাবার।',
    studentAlloc3:            'স্বাস্থ্যসেবা',
    studentAlloc3Desc:        'সকল শিক্ষার্থীর জন্য চিকিৎসা পরীক্ষা, চিকিৎসা ও স্বাস্থ্য সহায়তা।',
    studentFormTitle:         'অবদান রাখুন',
    studentSuccess:           'দান নথিভুক্ত হয়েছে! জাজাকাল্লাহ খাইর।',
    studentErrAmount:         'অনুগ্রহ করে সঠিক পরিমাণ লিখুন।',
    studentLabelName:         'আপনার নাম (ঐচ্ছিক)',
    studentLabelAmount:       'দানের পরিমাণ',
    studentCustomAmount:      'ইচ্ছামতো পরিমাণ',
    studentPaymentMethod:     'পেমেন্ট পদ্ধতি',
    studentProcessing:        'প্রক্রিয়া হচ্ছে…',
    // public nav
    home:           'হোম',
    about:          'আমাদের সম্পর্কে',
    admission:      'ভর্তি',
    donations:      'দান',
    zakat:          'যাকাত',
    gallery:        'গ্যালারি',
    transparency:   'স্বচ্ছতা',
    language:       'ভাষা',
    contact:        'যোগাযোগ',
    donateNow:      'এখনই দান করুন',
    // admin nav
    dashboard:      'ড্যাশবোর্ড',
    madrasaMgmt:    'মাদ্রাসা ব্যবস্থাপনা',
    students:       'শিক্ষার্থী',
    studentFinance: 'শিক্ষার্থী অর্থায়ন',
    adminDonations: 'দান ব্যবস্থাপনা',
    adminZakat:     'যাকাত ব্যবস্থাপনা',
    programs:       'প্রোগ্রামসমূহ',
    adminLanguage:  'ভাষা',
    reports:        'রিপোর্টসমূহ',
    users:          'ব্যবহারকারী',
    settings:       'সেটিংস',
    support:        'সহায়তা',
    logout:         'লগআউট',
    adminPortal:    'অ্যাডমিন পোর্টাল',
    adminConsole:   'অ্যাডমিন কনসোল',
    search:         'অনুসন্ধান…',
    // ZakatCalculatorPage
    zakatPageTitle:       'যাকাত ক্যালকুলেটর',
    zakatPageDesc:        'ইসলামী শরিয়াহ নীতির ভিত্তিতে সঠিকভাবে আপনার যাকাত হিসাব করুন। নিচে আপনার সম্পদ লিখুন।',
    zakatNisabInfo:       'নিসাব সীমা (রুপা)',
    zakatRate:            'হার: ২.৫%',
    zakatAssetsTitle:     'আপনার যাকাতযোগ্য সম্পদ',
    zakatAssetsSubtitle:  'এক পূর্ণ চান্দ্র বছর (হাওল) ধরে রাখা পরিমাণ লিখুন',
    zakatCalculate:       'যাকাত হিসাব করুন',
    zakatCalculating:     'হিসাব হচ্ছে…',
    zakatRulesTitle:      'ইসলামী যাকাতের নিয়মাবলী',
    zakatRule1:           'হাওল: সম্পদ এক পূর্ণ চান্দ্র বছর ধরে রাখতে হবে',
    zakatRule2:           'নিসাব: ৬১২.৩৬ গ্রাম রুপার ভিত্তিতে ন্যূনতম সীমা',
    zakatRule3:           'হার: মোট নিট যাকাতযোগ্য সম্পদের ২.৫%',
    zakatRule4:           'যাকাতযোগ্য: নগদ, সোনা, রুপা, বিনিয়োগ, ব্যবসায়িক পণ্য',
    zakatRule5:           'কর্তনযোগ্য: বছরের মধ্যে পরিশোধযোগ্য তাৎক্ষণিক ঋণ',
    zakatRule6:           'যাকাতযোগ্য নয়: ব্যক্তিগত বাড়ি, গাড়ি, পোশাক, আসবাবপত্র',
    zakatNisabMet:        'নিসাব সীমা পূর্ণ হয়েছে — যাকাত ফরজ',
    zakatNisabNotMet:     'নিসাব পূর্ণ হয়নি — যাকাত ফরজ নয়',
    zakatNisabLabel:      'নিসাব',
    zakatNetWealth:       'আপনার নিট সম্পদ',
    zakatBreakdownTitle:  'সম্পদের বিবরণ',
    zakatTotalAssets:     'মোট সম্পদ',
    zakatGoldValue:       'সোনার মূল্য',
    zakatSilverValue:     'রুপার মূল্য',
    zakatLessDebts:       'বাদ: ঋণ',
    zakatNetWealthLabel:  'নিট সম্পদ',
    zakatDueTitle:        'মোট প্রদেয় যাকাত',
    zakatAllocateTo:      'বরাদ্দ করুন',
    zakatPaymentMethod:   'পেমেন্ট পদ্ধতি',
    zakatDonorPlaceholder:'আপনার নাম (ঐচ্ছিক)',
    zakatRecorded:        'যাকাত নথিভুক্ত হয়েছে! জাজাকাল্লাহ খাইর।',
    zakatDonateBtn:       'দান করুন',
    zakatDonateNow:       'এখনই',
    zakatProcessing:      'প্রক্রিয়া হচ্ছে…',
    zakatErrZero:         'আপনার যাকাতের পরিমাণ ৳০। অনুগ্রহ করে আগে আপনার সম্পদ লিখুন।',
    zakatFieldCash:       'নগদ, ব্যাংক সঞ্চয় ও আমানত',
    zakatFieldCashHint:   'বাড়িতে এবং ব্যাংক অ্যাকাউন্টে সব নগদ অন্তর্ভুক্ত করুন',
    zakatFieldGold:       'সোনা (গ্রামে)',
    zakatFieldGoldHint:   'গ্রামে ওজন লিখুন — বর্তমান হারে মূল্য হিসাব হবে (৳৯,৫০০/গ্রাম)',
    zakatFieldSilver:     'রুপা (গ্রামে)',
    zakatFieldSilverHint: 'গ্রামে ওজন লিখুন — বর্তমান হারে মূল্য হিসাব হবে (৳১১০/গ্রাম)',
    zakatFieldInvest:     'বিনিয়োগ ও শেয়ার',
    zakatFieldInvestHint: 'বর্তমান বাজার মূল্যে স্টক, মিউচুয়াল ফান্ড এবং অন্যান্য বিনিয়োগ',
    zakatFieldBusiness:   'ব্যবসায়িক পণ্য ও মজুদ',
    zakatFieldBusinessHint:'বর্তমান বাজার মূল্যে ব্যবসার জন্য রাখা পণ্যের মূল্য',
    zakatFieldReceivable: 'আপনার পাওনা অর্থ',
    zakatFieldReceivableHint:'যে ঋণ দিয়েছেন এবং ফেরত পাওয়ার আশা রাখেন',
    zakatFieldDebts:      'কর্তনযোগ্য ঋণ',
    zakatFieldDebtsHint:  'বছরের মধ্যে পরিশোধযোগ্য তাৎক্ষণিক ঋণ (দীর্ঘমেয়াদী বন্ধক নয়)',
    zakatAlloc1:          'সাধারণ তহবিল (সবচেয়ে প্রয়োজনীয়)',
    zakatAlloc1Desc:      'যেখানে সবচেয়ে বেশি প্রয়োজন সেখানে বিতরণ',
    zakatAlloc2:          'শিক্ষার্থী স্পনসরশিপ',
    zakatAlloc2Desc:      'শিক্ষার্থীদের শিক্ষা সহায়তা',
    zakatAlloc3:          'মাদ্রাসা রক্ষণাবেক্ষণ',
    zakatAlloc3Desc:      'সুবিধাদির রক্ষণাবেক্ষণ',
    zakatAlloc4:          'ইসলামী শিক্ষা উপকরণ',
    zakatAlloc4Desc:      'বই ও শিক্ষার সম্পদ',
    // TransparencyDashboardPage
    transFinancialOverview:   'আর্থিক সংক্ষিপ্তসার',
    transHeroTitle:           'স্বচ্ছতা ও প্রভাব',
    transHeroDesc:            'আমরা সম্পূর্ণ জবাবদিহিতায় বিশ্বাস করি। আমাদের রিয়েল-টাইম আর্থিক বিতরণ, প্রকল্প ব্যয় এবং কার্যক্রমের সততা অন্বেষণ করুন।',
    transTotalDonations:      'মোট দান',
    transTotalDonors:         'জন মোট দাতা',
    transZakatCollected:      'সংগৃহীত যাকাত',
    transZakatVerified:       'যাচাইকৃত ও বিতরণকৃত',
    transActiveStudents:      'সক্রিয় শিক্ষার্থী',
    transCurrentlyEnrolled:   'বর্তমানে নিবন্ধিত',
    transFundDistTitle:       'প্রকল্প অনুযায়ী তহবিল বিতরণ',
    transMonthlyTitle:        'মাসিক দান (গত ৬ মাস)',
    transNoData:              'এখনো কোনো দানের তথ্য নেই।',
    transNoMonthly:           'কোনো মাসিক তথ্য পাওয়া যায়নি।',
    transProjectTitle:        'প্রকল্পের বিবরণ',
    transColProject:          'প্রকল্প',
    transColRaised:           'মোট সংগৃহীত',
    transColGoal:             'লক্ষ্য',
    transColProgress:         'অগ্রগতি',
    transColDonations:        'দান',
    transColStatus:           'অবস্থা',
    transNoProject:           'কোনো প্রকল্পের তথ্য পাওয়া যায়নি।',
    transStatusCompleted:     'সম্পন্ন',
    transStatusInProgress:    'চলমান',
    transStatusOngoing:       'অব্যাহত',
    transZakatFund:           'যাকাত তহবিল',
    transZakatDistributed:    'যাচাইকৃত ও যোগ্য প্রাপকদের মধ্যে বিতরণকৃত',
    transShariahCompliant:    'শরিয়াহ সম্মত',
    transShariahDesc:         'সমস্ত যাকাত ইসলামী নির্দেশিকা অনুযায়ী বিতরণ করা হয়',
    transDocsTitle:           'সরকারি দলিলপত্র',
    transDoc1:                'বার্ষিক প্রতিবেদন ২০২৩',
    transDoc1Size:            'পিডিএফ • ৪.২ এমবি',
    transDoc2:                'প্রথম প্রান্তিক আর্থিক বিবরণী ২০২৪',
    transDoc2Size:            'পিডিএফ • ১.১ এমবি',
    transDoc3:                'অডিট সার্টিফিকেট',
    transDoc3Size:            'পিডিএফ • ০.৮ এমবি',
    transDoc4:                'যাকাত নীতিমালা',
    transDoc4Size:            'পিডিএফ • ২.৫ এমবি',
    transTotal:               'মোট',
    // PhotoGalleryPage
    galleryTitle:             'দৃশ্যমান ইতিহাস',
    galleryDesc:              'আমাদের প্রাণবন্ত সমাজ, শিক্ষামূলক মাইলফলক এবং আপনার উদার অবদানের গভীর প্রভাবের একটি ঝলক।',
    galleryFilterAll:         'সব',
    galleryFilterQuran:       'কোরআন শিক্ষা',
    galleryFilterClassroom:   'শ্রেণিকক্ষ',
    galleryFilterEvents:      'অনুষ্ঠান',
    galleryFilterStudentLife: 'শিক্ষার্থী জীবন',
    galleryEmpty:             'এই বিভাগে এখনো কোনো ছবি নেই।',
    galleryLoadMore:          'আরও দেখুন',
    galleryRemaining:         'বাকি',
    // NotFoundPage
    notFoundTitle:    'পৃষ্ঠা পাওয়া যায়নি',
    notFoundDesc:     'আপনি যে পৃষ্ঠাটি খুঁজছেন সেটি সরানো হয়েছে, নাম পরিবর্তন করা হয়েছে, বা সাময়িকভাবে অনুপলব্ধ।',
    notFoundReturn:   'হোমে ফিরুন',
    notFoundContact:  'সহায়তায় যোগাযোগ করুন',
    notFoundFooter:   '© ২০২৪ মাদিনাতুল উলুম তাহফিজুল কোরআন মাদ্রাসা। সর্বস্বত্ব সংরক্ষিত।',
    // Footer
    footerTagline:      'প্রামাণিক ইসলামী শিক্ষা ও সহানুভূতিশীল দানের মাধ্যমে মন ও আত্মা গড়ে তুলতে নিবেদিত।',
    footerLicense:      'নিবন্ধিত এনজিও।',
    footerDonateTitle:  'দান',
    footerQuickTitle:   'দ্রুত লিংক',
    footerTransTitle:   'স্বচ্ছতা',
    footerLink1:        'যোগাযোগ করুন',
    footerLink2:        'ভর্তি পোর্টাল',
    footerLink3:        'আমাদের সম্পর্কে',
    footerLink4:        'ফটো গ্যালারি',
    footerLink5:        'স্বচ্ছতা',
    footerInfo1:        'স্বচ্ছতা ড্যাশবোর্ড',
    footerInfo2:        'ফটো গ্যালারি',
    footerInfo3:        'যাকাত ক্যালকুলেটর',
    footerDon1:         'সকল ক্যাম্পেইন',
    footerDon2:         'মাদ্রাসা উন্নয়ন তহবিল',
    footerDon3:         'মসজিদ সম্প্রসারণ তহবিল',
    footerDon4:         'শিক্ষার্থী সহায়তা তহবিল',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(
    () => localStorage.getItem('madrasa_lang') || LANGUAGES.BN
  );

  const [customOverrides, setCustomOverrides] = useState(() => {
    try {
      const stored = localStorage.getItem('madrasa_custom_translations');
      return stored ? JSON.parse(stored) : {};
    } catch { return {}; }
  });

  const toggleLang = useCallback(() => {
    setLang((prev) => {
      const next = prev === LANGUAGES.EN ? LANGUAGES.BN : LANGUAGES.EN;
      localStorage.setItem('madrasa_lang', next);
      return next;
    });
  }, []);

  const setCustomTranslations = useCallback((overrides) => {
    setCustomOverrides(overrides);
  }, []);

  const t = useCallback(
    (key) => customOverrides[key]?.[lang] ?? translations[lang]?.[key] ?? key,
    [lang, customOverrides]
  );

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t, setCustomTranslations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used inside LanguageProvider');
  return ctx;
}
