/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#00261b',
        'primary-container': '#0b3d2e',
        'on-primary': '#ffffff',
        'on-primary-container': '#79a894',
        'primary-fixed': '#bcedd7',
        'primary-fixed-dim': '#a0d1bc',
        'on-primary-fixed': '#002116',
        'on-primary-fixed-variant': '#214f3f',
        'inverse-primary': '#a0d1bc',
        'secondary': '#755b00',
        'secondary-container': '#fed255',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#735a00',
        'secondary-fixed': '#ffe08e',
        'secondary-fixed-dim': '#ecc246',
        'on-secondary-fixed': '#241a00',
        'on-secondary-fixed-variant': '#584400',
        'tertiary': '#3a1411',
        'tertiary-container': '#542925',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#cc8f88',
        'tertiary-fixed': '#ffdad6',
        'tertiary-fixed-dim': '#f9b6af',
        'on-tertiary-fixed': '#34100d',
        'on-tertiary-fixed-variant': '#693a35',
        'surface': '#f9faf7',
        'surface-dim': '#d9dad7',
        'surface-bright': '#f9faf7',
        'surface-base': '#FFFFFF',
        'surface-alt': '#F9F7F2',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f1',
        'surface-container': '#edeeeb',
        'surface-container-high': '#e7e8e6',
        'surface-container-highest': '#e2e3e0',
        'surface-variant': '#e2e3e0',
        'surface-tint': '#396756',
        'on-surface': '#1a1c1b',
        'on-surface-variant': '#414944',
        'inverse-surface': '#2e312f',
        'inverse-on-surface': '#f0f1ee',
        'background': '#f9faf7',
        'on-background': '#1a1c1b',
        'outline': '#717974',
        'outline-variant': '#c0c8c3',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'text-primary': '#1A1A1A',
        'text-muted': '#5C5C5C',
        'border-subtle': '#E5E1D8',
        'success-green': '#2D6A4F',
        'charity-gold-light': '#F1E6C5',
        'gold': '#C9A227',
      },
      fontFamily: {
        manrope: ['Manrope', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '24px',
        'stack-lg': '48px',
        'section-padding': '80px',
        'margin-mobile': '16px',
        'container-max': '1200px',
        'gutter': '24px',
        'unit': '4px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      boxShadow: {
        'ambient': '0 8px 24px rgba(11,61,46,0.08)',
        'ambient-lg': '0 12px 32px rgba(11,61,46,0.12)',
        'ambient-xl': '0 20px 40px rgba(11,61,46,0.15)',
      },
    },
  },
  plugins: [],
};
